name: 'Create pull request'
description: 'Creates a pull request, assign users and labels'
inputs:
  repo-token:
    description: 'Must be able to read all members of organization'
    default: ''
  repo:
    description: 'owner/repo-name'
    default: ''
  destination:
    description: 'Name of the destination branch'
    default: ''
  source:
    description: 'Name of the source branch'
    default: ''
  title:
    description: 'Title of the pull request'
    default: ''
  team-reviewers:
    description: 'List of comma-separated names of teams. All users contained in these teams will be individually asked for a review'
    default: ''
  user-reviewers:
    description: 'List of comma-separated logins of users'
    default: ''
  labels:
    description: 'List of comma-separated label names. If one does not exist, it will be created'
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Deprecated version of FinalCAD/CreatePullRequestAction
      shell: bash
      run: |
        echo '::error title=Deprecated version of FinalCAD/CreatePullRequestAction::This version of FinalCAD/CreatePullRequestAction is deprecated use `v1` instead.'
        exit 1
